# Generated by Django 5.2.4 on 2025-08-04 00:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='lugar_fin',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='anotacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anotacion',
            name='texto',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('lugar_fin', models.CharField(blank=True, max_length=100, null=True)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('anotacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectura_usada', to='libros.anotacion')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='libros.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='libros.usuario')),
            ],
        ),
    ]
