# Generated by Django 5.2.4 on 2025-08-19 13:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_remove_libro_comentario_remove_libro_fecha_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='lectura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='anotacion',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='lectura',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='anotacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='anotacion',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='lectura',
            name='anotacion',
        ),
        migrations.AddField(
            model_name='anotacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anotacion',
            name='lectura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='libros.lectura'),
        ),
        migrations.AddField(
            model_name='lectura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectura',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planeado'), ('READING', 'Leyendo'), ('FINISHED', 'Terminado'), ('ABANDONED', 'Abandonado')], db_index=True, default='PLANNED', max_length=10),
        ),
        migrations.AddField(
            model_name='lectura',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='openlibrary_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anotacion',
            name='pagina',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='puntaje',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo'], name='libros_libr_titulo_8b1204_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['autor'], name='libros_libr_autor_285ad2_idx'),
        ),
        migrations.AddConstraint(
            model_name='lectura',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PLANNED', 'READING'])), fields=('usuario', 'libro', 'status'), name='unique_active_read_per_user_book'),
        ),
        migrations.AddConstraint(
            model_name='lectura',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio')), ('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), _connector='OR'), name='end_date_after_start_date'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('usuario', 'libro')},
        ),
    ]
